(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(w>=1920){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1920){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/18-connecteur_autoradio-1178.jpg':'images/18-connecteur_autoradio-589.jpg');
var e=document.querySelector('.un3');e.setAttribute('src','images/image-collee-634-1.png');}else if($(window).width()>=1200){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/18-connecteur_autoradio-736.jpg':'images/18-connecteur_autoradio-368.jpg');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/image-collee-792.png':'images/image-collee-396.png');}else if($(window).width()>=960){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/18-connecteur_autoradio-588.jpg':'images/18-connecteur_autoradio-294-1.jpg');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/image-collee-634.png':'images/image-collee-317.png');}else if($(window).width()>=768){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/18-connecteur_autoradio-472.jpg':'images/18-connecteur_autoradio-236.jpg');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/image-collee-506.png':'images/image-collee-253.png');}else if($(window).width()>=480){var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/18-connecteur_autoradio-294.jpg':'images/18-connecteur_autoradio-147.jpg');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/image-collee-316.png':'images/image-collee-158.png');}else{var e=document.querySelector('.un1');e.setAttribute('src',(dpi>1)?'images/18-connecteur_autoradio-196.jpg':'images/18-connecteur_autoradio-98.jpg');
var e=document.querySelector('.un3');e.setAttribute('src',(dpi>1)?'images/image-collee-212.png':'images/image-collee-106.png');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var n=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));n||(n=1);var r=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];if(!r)return;var l=/chrome/i.test(navigator.userAgent);o=l?r.getBoundingClientRect().top*n+pageYOffset:(r.getBoundingClientRect().top+pageYOffset)*n}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var a=pageYOffset,i=null;requestAnimationFrame(function e(t){i||(i=t);var n=t-i;scrollTo(0,a<o?(o-a)*n/400+a:a-(a-o)*n/400),n<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
$('.un25').mouseenter(function() { $.loadImages('images/18-connecteur_autoradio-3024.jpg', function() { }) });
$('.un25').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un25-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/18-connecteur_autoradio-3024.jpg'; } } });
$('.un26').mouseenter(function() { $.loadImages('images/image-collee-748.png', function() { }) });
$('.un26').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade un26-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/image-collee-748.png'; } } });
wl=new woolite();
wl.init();
wl.addManualAnimation($('.un2'), "0.30s", "0.00s");
wl.addManualAnimation($('.un4'), "0.30s", "0.00s");
wl.start();
if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"0px"===window.getComputedStyle(document.body).getPropertyValue("min-width")&&setTimeout(o,100)};o()}

});